#!/usr/bin/env bash
# Exercises refresh-skills.sh (issue #92) in isolation: a fake WORKSPACE git
# repo, a stub dotagents-install.sh, and stub git/gh CLIs so no real npx
# download or GitHub call ever happens.
set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)"
SCRIPT="$ROOT/.devcontainer/refresh-skills.sh"
TMP="$(mktemp -d)"
trap 'rm -rf "$TMP"' EXIT

fail() { echo "FAIL: $*" >&2; exit 1; }

[[ -f $SCRIPT ]] || fail "refresh-skills.sh missing: $SCRIPT"

STUB_DIR="$TMP/stubs"
mkdir -p "$STUB_DIR"

GH_LOG="$TMP/gh.log"
TOKEN_LOG="$TMP/token.log"
GIT_PUSH_LOG="$TMP/git-push.log"
DOTAGENTS_LOG="$TMP/dotagents.log"
DOTAGENTS_INPUT_LOG="$TMP/dotagents-input.log"
RESOLUTION_MANIFEST_CAPTURE="$TMP/resolution-agents.toml"
GH_STATE_FILE="$TMP/gh-state"

write_lock_fixture() {
  local path="$1" alpha_commit="$2" beta_commit="$3"
  cat > "$path" <<EOF
# Auto-generated by dotagents. Do not edit.
version = 1

[skills.alpha-skill]
source = "fake/main"
resolved_url = "https://example.invalid/fake/main"
resolved_path = "skills/alpha-skill"
resolved_commit = "$alpha_commit"

[skills.beta-skill]
source = "fake/main"
resolved_url = "https://example.invalid/fake/main"
resolved_path = "skills/beta-skill"
resolved_commit = "$beta_commit"
EOF
}

LOCK_BASE="$TMP/lock-base.toml"
LOCK_V1="$TMP/lock-v1.toml"
LOCK_V2="$TMP/lock-v2.toml"
LOCK_V3="$TMP/lock-v3.toml"
LOCK_V4="$TMP/lock-v4.toml"
LOCK_FETCH_FAILURE="$TMP/lock-fetch-failure.toml"
LOCK_RACE_A="$TMP/lock-race-a.toml"
LOCK_RACE_B="$TMP/lock-race-b.toml"
LOCK_FEATURE_STAGED="$TMP/lock-feature-staged.toml"
LOCK_FEATURE_UNSTAGED="$TMP/lock-feature-unstaged.toml"
write_lock_fixture "$LOCK_BASE" 0000000000000000000000000000000000000001 0000000000000000000000000000000000000002
write_lock_fixture "$LOCK_V1" 1111111111111111111111111111111111111111 2222222222222222222222222222222222222222
write_lock_fixture "$LOCK_V2" 3333333333333333333333333333333333333333 4444444444444444444444444444444444444444
write_lock_fixture "$LOCK_V3" 5555555555555555555555555555555555555555 6666666666666666666666666666666666666666
write_lock_fixture "$LOCK_FETCH_FAILURE" 7777777777777777777777777777777777777777 8888888888888888888888888888888888888888
write_lock_fixture "$LOCK_V4" 9999999999999999999999999999999999999999 aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa
write_lock_fixture "$LOCK_RACE_A" bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb cccccccccccccccccccccccccccccccccccccccc
write_lock_fixture "$LOCK_RACE_B" dddddddddddddddddddddddddddddddddddddddd eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee
write_lock_fixture "$LOCK_FEATURE_STAGED" f111111111111111111111111111111111111111 f222222222222222222222222222222222222222
write_lock_fixture "$LOCK_FEATURE_UNSTAGED" f333333333333333333333333333333333333333 f444444444444444444444444444444444444444

cat > "$STUB_DIR/agents.toml" <<'EOF'
version = 1
agents = ["claude", "codex"]

[[skills]]
name = "stale-baked-skill"
source = "fake/stale"
EOF

# --- stub dotagents-install.sh: copies NEW_LOCK_FILE into $1/agents.lock
# when set, sleeps when SLEEP_SECS is set (to exercise the timeout), and
# fails when INSTALL_FAILS is set.
cat > "$STUB_DIR/dotagents-install.sh" <<'EOF'
#!/usr/bin/env bash
echo "$@" >> "$DOTAGENTS_LOG"
sha256sum "$1/agents.lock" | cut -d' ' -f1 >> "$DOTAGENTS_INPUT_LOG"
cp -n "$2/agents.toml" "$1/agents.toml"
[ "$1" = "$PRIMARY_WORKSPACE" ] || cp "$1/agents.toml" "$RESOLUTION_MANIFEST_CAPTURE"
[ "$1" != "$PRIMARY_WORKSPACE" ] || {
  [ -z "${RUNTIME_EARLY_LOCK_FILE:-}" ] || cp "$RUNTIME_EARLY_LOCK_FILE" "$1/agents.lock"
  [ -z "${RUNTIME_STARTED_FILE:-}" ] || : > "$RUNTIME_STARTED_FILE"
  [ -z "${RUNTIME_SLEEP_SECS:-}" ] || sleep "$RUNTIME_SLEEP_SECS"
  mkdir -p "$1/.agents/skills/runtime-proof"
  printf '/skills/runtime-proof\n' > "$1/.agents/.gitignore"
  printf 'runtime materialized\n' > "$1/.agents/skills/runtime-proof/SKILL.md"
}
[ "$1" = "$PRIMARY_WORKSPACE" ] || {
  [ -z "${RESOLUTION_STARTED_FILE:-}" ] || : > "$RESOLUTION_STARTED_FILE"
  [ -z "${RESOLUTION_SLEEP_SECS:-}" ] || sleep "$RESOLUTION_SLEEP_SECS"
}
if [ -n "${DESCENDANT_SLEEP_SECS:-}" ]; then
  ( sleep "$DESCENDANT_SLEEP_SECS"; : > "$DESCENDANT_DONE_FILE" ) &
  wait
fi
[ -z "${SLEEP_SECS:-}" ] || sleep "$SLEEP_SECS"
[ -z "${INSTALL_FAILS:-}" ] || { echo "dotagents: stub failure" >&2; exit 1; }
if [ -n "${NEW_LOCK_FILE:-}" ]; then
  cp "$NEW_LOCK_FILE" "$1/agents.lock"
fi
exit 0
EOF
chmod +x "$STUB_DIR/dotagents-install.sh"

# --- stub gh-app-token.sh: always "succeeds" with a fake token ---
cat > "$STUB_DIR/gh-app-token.sh" <<'EOF'
#!/usr/bin/env bash
printf '%s\n' "${GITHUB_APP_REPO:-}" >> "$TOKEN_LOG"
echo "fake-token"
EOF
chmod +x "$STUB_DIR/gh-app-token.sh"

# --- stub gh: records every invocation; `pr list` result controlled by
# EXISTING_PR_URL, `pr create` "succeeds" printing a fixed URL unless
# PR_CREATE_FAILS is set ---
cat > "$STUB_DIR/gh" <<'EOF'
#!/usr/bin/env bash
echo "$*" >> "$GH_LOG"
if [ "$1" = pr ] && [ "$2" = list ]; then
  if [ -n "${EXISTING_PR_URL:-}" ]; then
    printf '%s\n' "$EXISTING_PR_URL"
  elif [ -s "$GH_STATE_FILE" ]; then
    cat "$GH_STATE_FILE"
  fi
  exit 0
fi
if [ "$1" = pr ] && [ "$2" = create ]; then
  [ -z "${PR_CREATE_FAILS:-}" ] || { echo "gh: stub pr create failure" >&2; exit 1; }
  echo "https://github.com/fake/repo/pull/999"
  echo "https://github.com/fake/repo/pull/999" > "$GH_STATE_FILE"
  exit 0
fi
exit 0
EOF
chmod +x "$STUB_DIR/gh"

# Production bypasses PATH-level gh shims after minting a token. Redirect that
# fixed target only in this fixture copy, avoiding a host GitHub CLI call.
TEST_SCRIPT="$TMP/refresh-skills-under-test.sh"
sed "s|/usr/bin/gh|$STUB_DIR/gh|g" "$SCRIPT" > "$TEST_SCRIPT"
chmod +x "$TEST_SCRIPT"

# --- stub git: passes through to the real git for everything except
# `push`, which is recorded and can be made to fail ---
REAL_GIT="$(command -v git)"
cat > "$STUB_DIR/git" <<EOF
#!/usr/bin/env bash
REAL_GIT="$REAL_GIT"
EOF
cat >> "$STUB_DIR/git" <<'EOF'
# refresh-skills.sh always calls git as `git -C <dir> <subcommand> ...`, so
# $1 is "-C", not the subcommand — match "push" anywhere in the argv instead.
case " $* " in
  *' fetch '*)
    [ -z "${GIT_FETCH_FAILS:-}" ] || { echo "git: stub fetch failure" >&2; exit 1; }
    ;;
  *' push '*)
    echo "$@" >> "$GIT_PUSH_LOG"
    [ -z "${GIT_PUSH_FAILS:-}" ] || { echo "git: stub push failure" >&2; exit 1; }
    exec "$REAL_GIT" -C "$2" push --no-verify "${@:4}"
    ;;
esac
exec "$REAL_GIT" "$@"
EOF
chmod +x "$STUB_DIR/git"

STUB_PATH="$STUB_DIR:$PATH"

# --- a real git repo standing in for the primary WORKSPACE, with a tracked
# agents.lock so `git diff -- agents.lock` / `git checkout -- agents.lock`
# behave like the real thing ---
WORKSPACE_DIR="$TMP/ws"
mkdir -p "$WORKSPACE_DIR"
git -C "$WORKSPACE_DIR" init -q -b main
git -C "$WORKSPACE_DIR" config user.email test@example.com
git -C "$WORKSPACE_DIR" config user.name "Test"
mkdir -p "$WORKSPACE_DIR/.devcontainer"
cat > "$WORKSPACE_DIR/.devcontainer/agents.toml" <<'EOF'
version = 1
agents = ["claude", "codex"]

[[skills]]
name = "alpha-skill"
source = "fake/main"

[[skills]]
name = "beta-skill"
source = "fake/main"
EOF
cp "$LOCK_BASE" "$WORKSPACE_DIR/agents.lock"
printf '/.agents/.gitignore\n/agents.toml\n' > "$WORKSPACE_DIR/.gitignore"
git -C "$WORKSPACE_DIR" add agents.lock .gitignore .devcontainer/agents.toml
git -C "$WORKSPACE_DIR" commit -qm "seed agents.lock"
# `git push` is stubbed above, but `refresh-skills.sh` still needs a remote
# named `origin` to push to and a real one to fetch from for `worktree add`.
REMOTE_DIR="$TMP/remote.git"
git init -q --bare "$REMOTE_DIR"
git -C "$WORKSPACE_DIR" remote add origin "$REMOTE_DIR"
# --no-verify: this pushes to a throwaway local bare repo standing in for
# `origin`, not the real project remote — the global pre-push hook installed
# by setup-agents.sh (blocks direct pushes to main) would otherwise fire here.
git -C "$WORKSPACE_DIR" push -q --no-verify origin main
git -C "$WORKSPACE_DIR" branch --set-upstream-to=origin/main main -q

GITHUB_APP_DIR="$TMP/github-app"
mkdir -p "$GITHUB_APP_DIR"
printf 'dummy-key\n' > "$GITHUB_APP_DIR/private-key.pem"
printf '1\n' > "$GITHUB_APP_DIR/app-id"

# run ENV... ; sets STATUS and OUT, never aborts the suite
run() {
  set +e
  OUT="$(env "$@" \
    WORKSPACE="$WORKSPACE_DIR" TOOLDIR="$STUB_DIR" PROJECT_NAME=proj GH_OWNER=owner \
    GITHUB_APP_DIR="$GITHUB_APP_DIR" GH_LOG="$GH_LOG" TOKEN_LOG="$TOKEN_LOG" GIT_PUSH_LOG="$GIT_PUSH_LOG" \
    DOTAGENTS_LOG="$DOTAGENTS_LOG" DOTAGENTS_INPUT_LOG="$DOTAGENTS_INPUT_LOG" GH_STATE_FILE="$GH_STATE_FILE" \
    RESOLUTION_MANIFEST_CAPTURE="$RESOLUTION_MANIFEST_CAPTURE" PRIMARY_WORKSPACE="$WORKSPACE_DIR" PATH="$STUB_PATH" \
    bash "$TEST_SCRIPT" 2>&1)"
  STATUS=$?
  set -e
}

reset_workspace() {
  git -C "$WORKSPACE_DIR" checkout -q main
  git -C "$WORKSPACE_DIR" reset -q --hard origin/main
  git -C "$WORKSPACE_DIR" clean -qfdx
  : > "$GH_LOG"; : > "$TOKEN_LOG"; : > "$GIT_PUSH_LOG"; : > "$DOTAGENTS_LOG"
  : > "$DOTAGENTS_INPUT_LOG"; : > "$GH_STATE_FILE"
  : > "$RESOLUTION_MANIFEST_CAPTURE"
}
gh_call_count() { grep -c '^pr ' "$GH_LOG" 2>/dev/null || true; }

# =========================================================================
# Case 1: WORKSPACE is not a git repo -> one line, exit 0, install never run.
# =========================================================================
NON_REPO="$TMP/not-a-repo"
mkdir -p "$NON_REPO"
set +e
OUT="$(WORKSPACE="$NON_REPO" TOOLDIR="$STUB_DIR" PROJECT_NAME=proj GH_OWNER=owner \
  GITHUB_APP_DIR="$GITHUB_APP_DIR" DOTAGENTS_LOG="$DOTAGENTS_LOG" TOKEN_LOG="$TOKEN_LOG" PATH="$STUB_PATH" \
  bash "$TEST_SCRIPT" 2>&1)"
STATUS=$?
set -e
[[ $STATUS -eq 0 ]] || fail "case 1: exited $STATUS, expected 0: $OUT"
[[ ! -s $DOTAGENTS_LOG ]] || fail "case 1: dotagents-install.sh was invoked on a non-repo WORKSPACE"
[[ "$OUT" == *"not a git repository"* ]] || fail "case 1: expected an explanatory line, got: $OUT"

# =========================================================================
# Case 2: dotagents-install.sh missing at TOOLDIR -> one line, exit 0.
# =========================================================================
EMPTY_TOOLDIR="$TMP/empty-tooldir"
mkdir -p "$EMPTY_TOOLDIR"
reset_workspace
set +e
OUT="$(WORKSPACE="$WORKSPACE_DIR" TOOLDIR="$EMPTY_TOOLDIR" PROJECT_NAME=proj GH_OWNER=owner \
  GITHUB_APP_DIR="$GITHUB_APP_DIR" TOKEN_LOG="$TOKEN_LOG" PATH="$STUB_PATH" bash "$TEST_SCRIPT" 2>&1)"
STATUS=$?
set -e
[[ $STATUS -eq 0 ]] || fail "case 2: exited $STATUS, expected 0: $OUT"
[[ "$OUT" == *"dotagents-install.sh"*"not found"* ]] || fail "case 2: expected a not-found line, got: $OUT"

# =========================================================================
# Case 3: dotagents-install.sh hangs past a bounded timeout -> WARNING
# mentions the timeout, exit 0. REFRESH_SKILLS_TIMEOUT overrides the
# production 120s bound so the test stays fast.
# =========================================================================
reset_workspace
TIMEOUT_STARTED_MS="$(date +%s%3N)"
run DESCENDANT_SLEEP_SECS=4 DESCENDANT_DONE_FILE="$TMP/descendant-finished" REFRESH_SKILLS_TIMEOUT=1
TIMEOUT_ELAPSED_MS=$(( $(date +%s%3N) - TIMEOUT_STARTED_MS ))
[[ $STATUS -eq 0 ]] || fail "case 3: exited $STATUS, expected 0: $OUT"
[[ "$OUT" == *"timed out"* ]] || fail "case 3: expected a timeout warning, got: $OUT"
[[ "$TIMEOUT_ELAPSED_MS" -lt 3500 ]] || \
  fail "case 3: helper descendants extended two 1s timeouts to ${TIMEOUT_ELAPSED_MS}ms"
[[ ! -e "$TMP/descendant-finished" ]] || fail "case 3: timed-out helper descendant survived"

# =========================================================================
# Case 4: dotagents-install.sh fails outright -> WARNING, exit 0, no bump.
# =========================================================================
reset_workspace
run INSTALL_FAILS=1
[[ $STATUS -eq 0 ]] || fail "case 4: exited $STATUS, expected 0: $OUT"
[[ "$OUT" == *"WARNING"* ]] || fail "case 4: expected a WARNING, got: $OUT"
[[ "$(gh_call_count)" -eq 0 ]] || fail "case 4: gh was called despite install failing"

# =========================================================================
# Case 5: install succeeds, agents.lock unchanged -> no worktree/push/gh
# calls at all, and no WARNING.
# =========================================================================
reset_workspace
run
[[ $STATUS -eq 0 ]] || fail "case 5: exited $STATUS, expected 0: $OUT"
[[ -s $DOTAGENTS_LOG ]] || fail "case 5: dotagents-install.sh was never invoked"
[[ -f "$WORKSPACE_DIR/.agents/skills/runtime-proof/SKILL.md" ]] || \
  fail "case 5: runtime skills were not materialized in the primary workspace"
cmp -s "$WORKSPACE_DIR/.devcontainer/agents.toml" "$RESOLUTION_MANIFEST_CAPTURE" || \
  fail "case 5: resolution used baked TOOLDIR manifest instead of origin/main manifest"
[[ "$(gh_call_count)" -eq 0 ]] || fail "case 5: gh was called despite no agents.lock diff"
git --git-dir="$REMOTE_DIR" show-ref --verify --quiet refs/heads/agent/agents-lock-upgrade && \
  fail "case 5: no-change resolution published a bump branch"
[[ "$OUT" != *WARNING* ]] || fail "case 5: unexpected WARNING with no diff: $OUT"

# =========================================================================
# Case 6: install produces a diff, on main, no existing open PR -> gh pr
# create is called once with the fixed branch; agents.lock ends up restored
# to its tracked content.
# =========================================================================
reset_workspace
run NEW_LOCK_FILE="$LOCK_V1"
[[ $STATUS -eq 0 ]] || fail "case 6: exited $STATUS, expected 0: $OUT"
grep -Fq 'pr list' "$GH_LOG" || fail "case 6: expected a gh pr list existing-PR check: $(cat "$GH_LOG")"
grep -Fq 'pr create' "$GH_LOG" || fail "case 6: expected gh pr create to run: $(cat "$GH_LOG")"
grep -Fq -- '--head agent/agents-lock-upgrade' "$GH_LOG" || \
  fail "case 6: expected the fixed bump branch name: $(cat "$GH_LOG")"
[[ "$(wc -l < "$TOKEN_LOG")" -eq 2 ]] || \
  fail "case 6: expected one token mint per gh call: $(cat "$TOKEN_LOG")"
[[ "$OUT" == *"https://github.com/fake/repo/pull/999"* ]] || fail "case 6: expected the PR URL reported: $OUT"
cmp -s "$LOCK_BASE" "$WORKSPACE_DIR/agents.lock" || \
  fail "case 6: primary agents.lock was not restored"
[[ -z "$(git -C "$WORKSPACE_DIR" status --porcelain)" ]] || \
  fail "case 6: primary worktree left dirty: $(git -C "$WORKSPACE_DIR" status --porcelain)"

# =========================================================================
# Case 7: same, but a PR is already open for the fixed branch -> gh pr
# create is NOT called; the branch is still force-pushed with new content.
# =========================================================================
reset_workspace
run NEW_LOCK_FILE="$LOCK_V2" EXISTING_PR_URL=https://github.com/fake/repo/pull/42
[[ $STATUS -eq 0 ]] || fail "case 7: exited $STATUS, expected 0: $OUT"
grep -Fq 'pr list' "$GH_LOG" || fail "case 7: expected a gh pr list check: $(cat "$GH_LOG")"
grep -Fq 'pr create' "$GH_LOG" && fail "case 7: gh pr create should not run when a PR is already open: $(cat "$GH_LOG")"
[[ "$(wc -l < "$TOKEN_LOG")" -eq 1 ]] || \
  fail "case 7: expected one token mint for the gh pr list: $(cat "$TOKEN_LOG")"
[[ -s $GIT_PUSH_LOG ]] || fail "case 7: expected the bump branch to still be pushed"
[[ "$OUT" == *"https://github.com/fake/repo/pull/42"* ]] || fail "case 7: expected the existing PR URL reported: $OUT"
cmp -s "$LOCK_BASE" "$WORKSPACE_DIR/agents.lock" || \
  fail "case 7: primary agents.lock was not restored"

# =========================================================================
# Case 8 (#108): staged and unstaged feature-branch agents.lock edits survive
# byte-for-byte. Resolution runs from origin/main's lock, never from either
# feature-branch layer, and still opens the bump PR.
# =========================================================================
reset_workspace
git -C "$WORKSPACE_DIR" checkout -qB feature
cp "$LOCK_FEATURE_STAGED" "$WORKSPACE_DIR/agents.lock"
git -C "$WORKSPACE_DIR" add agents.lock
git -C "$WORKSPACE_DIR" show :agents.lock > "$TMP/feature-staged.expected"
cp "$LOCK_FEATURE_UNSTAGED" "$WORKSPACE_DIR/agents.lock"
cp "$WORKSPACE_DIR/agents.lock" "$TMP/feature-unstaged.expected"
run NEW_LOCK_FILE="$LOCK_V3"
[[ $STATUS -eq 0 ]] || fail "case 8: exited $STATUS, expected 0: $OUT"
grep -Fq 'pr create' "$GH_LOG" || fail "case 8: expected gh pr create to run on a feature branch: $(cat "$GH_LOG")"
git -C "$WORKSPACE_DIR" show :agents.lock > "$TMP/feature-staged.actual"
cmp -s "$TMP/feature-staged.expected" "$TMP/feature-staged.actual" || \
  fail "case 8: staged agents.lock edit was changed"
cmp -s "$TMP/feature-unstaged.expected" "$WORKSPACE_DIR/agents.lock" || \
  fail "case 8: unstaged agents.lock edit was changed"
[[ "$(git -C "$WORKSPACE_DIR" status --porcelain -- agents.lock)" == "MM agents.lock" ]] || \
  fail "case 8: agents.lock index/worktree state changed: $(git -C "$WORKSPACE_DIR" status --porcelain -- agents.lock)"
[[ "$(sed -n '1p' "$DOTAGENTS_INPUT_LOG")" == "$(sha256sum "$LOCK_FEATURE_UNSTAGED" | cut -d' ' -f1)" ]] || \
  fail "case 8: runtime installation did not use the primary lock state: $(cat "$DOTAGENTS_INPUT_LOG")"
[[ "$(sed -n '2p' "$DOTAGENTS_INPUT_LOG")" == "$(sha256sum "$LOCK_BASE" | cut -d' ' -f1)" ]] || \
  fail "case 8: bump resolution did not start from origin/main: $(cat "$DOTAGENTS_INPUT_LOG")"
git --git-dir="$REMOTE_DIR" show refs/heads/agent/agents-lock-upgrade:agents.lock > "$TMP/case8-published.lock"
cmp -s "$LOCK_V3" "$TMP/case8-published.lock" || \
  fail "case 8: feature-branch agents.lock edits leaked into the published lock"
[[ "$OUT" == *"https://github.com/fake/repo/pull/999"* ]] || fail "case 8: expected the PR URL reported: $OUT"
git -C "$WORKSPACE_DIR" reset -q --hard
git -C "$WORKSPACE_DIR" checkout -q main

# =========================================================================
# Case 9: fetch failure is nonfatal and never starts resolution or publication.
# =========================================================================
reset_workspace
run NEW_LOCK_FILE="$LOCK_FETCH_FAILURE" GIT_FETCH_FAILS=1
[[ $STATUS -eq 0 ]] || fail "case 9: exited $STATUS, expected 0: $OUT"
[[ "$OUT" == *"fetching origin/main failed"* ]] || fail "case 9: expected fetch warning, got: $OUT"
[[ "$(wc -l < "$DOTAGENTS_LOG")" -eq 1 ]] || \
  fail "case 9: expected only primary runtime installation after fetch failure: $(cat "$DOTAGENTS_LOG")"
[[ "$(cut -d' ' -f1 "$DOTAGENTS_LOG")" == "$WORKSPACE_DIR" ]] || \
  fail "case 9: runtime installation missed primary workspace: $(cat "$DOTAGENTS_LOG")"
[[ -f "$WORKSPACE_DIR/.agents/skills/runtime-proof/SKILL.md" ]] || \
  fail "case 9: fetch failure prevented independent runtime materialization"
[[ ! -s "$GIT_PUSH_LOG" ]] || fail "case 9: push ran after fetch failed: $(cat "$GIT_PUSH_LOG")"
[[ "$(gh_call_count)" -eq 0 ]] || fail "case 9: gh ran after fetch failed: $(cat "$GH_LOG")"
[[ -z "$(git -C "$WORKSPACE_DIR" status --porcelain)" ]] || \
  fail "case 9: primary worktree changed after fetch failure: $(git -C "$WORKSPACE_DIR" status --porcelain)"

# =========================================================================
# Case 10: git push fails -> "auto-PR failed" WARNING, agents.lock still
# restored, gh pr create never reached.
# =========================================================================
reset_workspace
PUSH_FAILURE_BASELINE="$(git --git-dir="$REMOTE_DIR" rev-parse refs/heads/agent/agents-lock-upgrade)"
run NEW_LOCK_FILE="$LOCK_V4" GIT_PUSH_FAILS=1
[[ $STATUS -eq 0 ]] || fail "case 10: exited $STATUS, expected 0: $OUT"
[[ "$OUT" == *"auto-PR failed"* ]] || fail "case 10: expected an auto-PR-failed warning, got: $OUT"
grep -Fq 'pr create' "$GH_LOG" && fail "case 10: gh pr create should not run after a failed push: $(cat "$GH_LOG")"
[[ "$(git --git-dir="$REMOTE_DIR" rev-parse refs/heads/agent/agents-lock-upgrade)" == "$PUSH_FAILURE_BASELINE" ]] || \
  fail "case 10: failed push changed the published bump branch"
cmp -s "$LOCK_BASE" "$WORKSPACE_DIR/agents.lock" || \
  fail "case 10: primary agents.lock was not restored after a failed push"

# =========================================================================
# Case 11 (#108): two refresh runs racing the same bump branch (postCreate
# and postStart overlapping) serialize instead of corrupting the shared
# `git worktree add -B` — both exit 0, and only one worktree entry for the
# bump branch survives.
# =========================================================================
reset_workspace
STATUS_A_FILE="$TMP/status-a"
STATUS_B_FILE="$TMP/status-b"
run_bg() {
  local status_file="$1" output_file="$2"; shift 2
  env "$@" WORKSPACE="$WORKSPACE_DIR" TOOLDIR="$STUB_DIR" PROJECT_NAME=proj GH_OWNER=owner \
    GITHUB_APP_DIR="$GITHUB_APP_DIR" GH_LOG="$GH_LOG" TOKEN_LOG="$TOKEN_LOG" GIT_PUSH_LOG="$GIT_PUSH_LOG" \
    DOTAGENTS_LOG="$DOTAGENTS_LOG" DOTAGENTS_INPUT_LOG="$DOTAGENTS_INPUT_LOG" GH_STATE_FILE="$GH_STATE_FILE" \
    RESOLUTION_MANIFEST_CAPTURE="$RESOLUTION_MANIFEST_CAPTURE" PRIMARY_WORKSPACE="$WORKSPACE_DIR" \
    PATH="$STUB_PATH" bash "$TEST_SCRIPT" >"$output_file" 2>&1
  echo $? > "$status_file"
}
OUT_A_FILE="$TMP/out-a"
OUT_B_FILE="$TMP/out-b"
run_bg "$STATUS_A_FILE" "$OUT_A_FILE" NEW_LOCK_FILE="$LOCK_RACE_A" SLEEP_SECS=2 &
for _ in $(seq 1 100); do
  [[ -s "$DOTAGENTS_LOG" ]] && break
  sleep 0.02
done
[[ -s "$DOTAGENTS_LOG" ]] || fail "case 11: run A never entered resolution"
run_bg "$STATUS_B_FILE" "$OUT_B_FILE" NEW_LOCK_FILE="$LOCK_RACE_B" &
wait
[[ "$(cat "$STATUS_A_FILE")" -eq 0 ]] || fail "case 11: concurrent run A exited nonzero"
[[ "$(cat "$STATUS_B_FILE")" -eq 0 ]] || fail "case 11: concurrent run B exited nonzero"
git --git-dir="$REMOTE_DIR" show refs/heads/agent/agents-lock-upgrade:agents.lock > "$TMP/race-published.lock"
cmp -s "$LOCK_RACE_B" "$TMP/race-published.lock" || \
  fail "case 11: published lock did not come from serialized final run"
grep -Fq '[skills.alpha-skill]' "$TMP/race-published.lock" || fail "case 11: alpha skill missing from published lock"
grep -Fq 'resolved_commit = "dddddddddddddddddddddddddddddddddddddddd"' "$TMP/race-published.lock" || \
  fail "case 11: alpha commit corrupted in published lock"
grep -Fq '[skills.beta-skill]' "$TMP/race-published.lock" || fail "case 11: beta skill missing from published lock"
grep -Fq 'resolved_commit = "eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee"' "$TMP/race-published.lock" || \
  fail "case 11: beta commit corrupted in published lock"
[[ "$(grep -c '^pr create' "$GH_LOG" 2>/dev/null || true)" -eq 1 ]] || \
  fail "case 11: concurrent runs created more than one PR: $(cat "$GH_LOG")"
[[ "$(git -C "$WORKSPACE_DIR" worktree list --porcelain | grep -c '^worktree ' 2>/dev/null || true)" -eq 1 ]] || \
  fail "case 11: disposable worktree survived concurrent refreshes"
[[ -z "$(git -C "$WORKSPACE_DIR" status --porcelain)" ]] || \
  fail "case 11: primary worktree left dirty after a concurrent bump: $(git -C "$WORKSPACE_DIR" status --porcelain)"

# =========================================================================
# Case 12 (#108): TERM cleans a live deterministic resolution worktree. A
# subsequent untrappable crash may leave it behind, but the next refresh
# recovers that exact repo-scoped path and its Git metadata before reuse.
# =========================================================================
start_interruptible() {
  local output_file="$1"; shift
  setsid env "$@" WORKSPACE="$WORKSPACE_DIR" TOOLDIR="$STUB_DIR" PROJECT_NAME=proj GH_OWNER=owner \
    GITHUB_APP_DIR="$GITHUB_APP_DIR" GH_LOG="$GH_LOG" TOKEN_LOG="$TOKEN_LOG" GIT_PUSH_LOG="$GIT_PUSH_LOG" \
    DOTAGENTS_LOG="$DOTAGENTS_LOG" DOTAGENTS_INPUT_LOG="$DOTAGENTS_INPUT_LOG" GH_STATE_FILE="$GH_STATE_FILE" \
    RESOLUTION_MANIFEST_CAPTURE="$RESOLUTION_MANIFEST_CAPTURE" PRIMARY_WORKSPACE="$WORKSPACE_DIR" \
    PATH="$STUB_PATH" bash "$TEST_SCRIPT" >"$output_file" 2>&1 &
  INTERRUPT_PID=$!
}

wait_for_marker() {
  local marker="$1"
  for _ in $(seq 1 200); do
    [[ -e "$marker" ]] && return 0
    sleep 0.02
  done
  fail "case 12: interrupted phase never started"
}

wait_for_resolution_cleanup() {
  for _ in $(seq 1 200); do
    if [[ ! -e "$RESOLUTION_WT" ]] &&
       [[ "$(git -C "$WORKSPACE_DIR" worktree list --porcelain | grep -c '^worktree ')" -eq 1 ]]; then
      return 0
    fi
    sleep 0.02
  done
  return 1
}

kill_interruptible_hard() {
  ACTIVE_INSTALL_FILE="$WORKSPACE_DIR/.git/agents-lock-active-install"
  [[ -s "$ACTIVE_INSTALL_FILE" ]] || fail "case 12: active installer process group was not recorded"
  STALE_INSTALL_PID="$(cat "$ACTIVE_INSTALL_FILE")"
  kill -KILL -- "-$INTERRUPT_PID"
}

reset_workspace
RESOLUTION_WT="$WORKSPACE_DIR/.git/agents-lock-refresh-worktree"
TERM_MARKER="$TMP/term-resolution-started"
start_interruptible "$TMP/term.out" RESOLUTION_STARTED_FILE="$TERM_MARKER" RESOLUTION_SLEEP_SECS=30
wait_for_marker "$TERM_MARKER"
kill -TERM -- "-$INTERRUPT_PID"
set +e
wait "$INTERRUPT_PID" 2>/dev/null
set -e
wait_for_resolution_cleanup || fail "case 12: TERM cleanup did not finish"
[[ ! -e "$RESOLUTION_WT" ]] || fail "case 12: TERM left deterministic resolution directory behind"
[[ "$(git -C "$WORKSPACE_DIR" worktree list --porcelain | grep -c '^worktree ')" -eq 1 ]] || \
  fail "case 12: TERM left resolution worktree metadata behind"

KILL_MARKER="$TMP/kill-resolution-started"
start_interruptible "$TMP/kill.out" RESOLUTION_STARTED_FILE="$KILL_MARKER" RESOLUTION_SLEEP_SECS=30
wait_for_marker "$KILL_MARKER"
kill_interruptible_hard
KILLED_RESOLUTION_INSTALL_PID="$STALE_INSTALL_PID"
set +e
wait "$INTERRUPT_PID" 2>/dev/null
set -e
[[ -d "$RESOLUTION_WT" ]] || fail "case 12: resolution worktree path is not deterministic and repo-scoped"
run
[[ $STATUS -eq 0 ]] || fail "case 12: restart after interrupted refresh exited $STATUS: $OUT"
[[ ! -e "$RESOLUTION_WT" ]] || fail "case 12: restart left recovered resolution directory behind"
[[ "$(git -C "$WORKSPACE_DIR" worktree list --porcelain | grep -c '^worktree ')" -eq 1 ]] || \
  fail "case 12: restart left stale worktree metadata behind"
kill -0 "$KILLED_RESOLUTION_INSTALL_PID" 2>/dev/null && \
  fail "case 12: restart left interrupted resolution descendant running"

# A crash during primary materialization leaves the preserved lock snapshot;
# startup recovery must restore it before retrying either installation phase.
reset_workspace
RUNTIME_MARKER="$TMP/runtime-started"
start_interruptible "$TMP/runtime-kill.out" RUNTIME_STARTED_FILE="$RUNTIME_MARKER" \
  RUNTIME_SLEEP_SECS=30 RUNTIME_EARLY_LOCK_FILE="$LOCK_V4"
wait_for_marker "$RUNTIME_MARKER"
kill_interruptible_hard
KILLED_RUNTIME_INSTALL_PID="$STALE_INSTALL_PID"
set +e
wait "$INTERRUPT_PID" 2>/dev/null
set -e
cmp -s "$LOCK_V4" "$WORKSPACE_DIR/agents.lock" || \
  fail "case 12: runtime crash did not exercise overwritten primary lock"
[[ -d "$WORKSPACE_DIR/.git/agents-lock-primary-state" ]] || \
  fail "case 12: runtime crash left no recoverable primary lock snapshot"
run
[[ $STATUS -eq 0 ]] || fail "case 12: restart after runtime crash exited $STATUS: $OUT"
cmp -s "$LOCK_BASE" "$WORKSPACE_DIR/agents.lock" || \
  fail "case 12: restart did not restore primary lock after runtime crash"
[[ ! -e "$WORKSPACE_DIR/.git/agents-lock-primary-state" ]] || \
  fail "case 12: restart left primary lock recovery state behind"
kill -0 "$KILLED_RUNTIME_INSTALL_PID" 2>/dev/null && \
  fail "case 12: restart left interrupted runtime descendant running"
[[ -z "$(git -C "$WORKSPACE_DIR" status --porcelain)" ]] || \
  fail "case 12: restart after runtime crash changed tracked primary state"

echo "PASS: refresh-skills.test.sh"
